name: thesis
channels:
  - conda-forge
dependencies:
  - python=3.13.2

  # Notebook
  - ipykernel
  - jupyter
  - jupyterlab

  # Data Science
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn

  # DB / Konfiguration
  - sqlalchemy
  - psycopg
  - libpq  
  - python-dotenv

  # File formats
  - pyarrow
  
  # Test / Tooling
  - pytest
  - pip
  # Installiere das lokale Projekt als Paket (src/mph wird importierbar)
  - pip:
      - -e .