name: thesis
channels:
  - conda-forge
dependencies:
  - python=3.13.2
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - sqlalchemy
  - pytest
  - python-dotenv
  # Postgres-Treiber (empfohlen f√ºr SQLAlchemy)
  - psycopg
  - libpq
  - pip
